import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Button from "@material-ui/core/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Basics</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main className={styles.main}>
        <div>
        <Link href="/static1">
          <Button variant="contained" color="danger">Static 1</Button>
        </Link>
        <Link href="/static2">
          <Button variant="contained" color="primary">Static 2</Button>
        </Link>
        <Link href="/static3">
          <Button variant="contained" color="secondary">Static 3</Button>
        </Link>
        <Link href="/dynamic1">
          <Button variant="contained" color="secondary">Dynamic 1</Button>
        </Link>
        <Link href="/dynamic2">
          <Button variant="contained" color="secondary">Dynamic 2</Button>
        </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by <span className={styles.logo}></span>
      </footer>
    </div>
  );
}
